### ISSUE TITLE
More memory retained by hashes than by roots?

### ISSUE THREAD

**Issue by 97jaz** [djudd/reap#1]
Hi, I'm looking at output like this:
```
Object types retaining the most live memory:
Hash: 1010.1 MB (10510995 objects)
Array: 706.5 MB (7566193 objects)
ROOT: 615.8 MB (5365383 objects)
Thread: 494.9 MB (4833542 objects)
[...]
```
... and I'm having trouble interpreting this. I'd have thought that any memory retained by a hash would also have to be retained by a GC root, so `ROOT` would always be at the top of this list. Is this because, since multiple objects can have pointers to the same object, the same memory can be counted multiple times?

**Comment by djudd** [comment]
I haven't used this tool for a bit so I might be wrong, but I believe that you're right that there can be double counting in the "retaining the most live memory" list. It's not about multiple objects A, B, C all having pointers to some given object X, because the dominator tree approach should ensure that we either pick one of A, B, C as the root (if say, A has pointers to B & C but not vice versa) or ignore them all in favor of something that retains all of them. Rather, if you have A -> B -> C -> X, all dominating, we'll count all of X's memory towards each of C, B, and A. So if A, B, and C are all hashes, we could end up with something like what you see.

You might (or might not) be able to get a better sense of what's happening by looking at some of the graphical output.

**Comment by 97jaz** [comment]
> Rather, if you have A -> B -> C -> X, all dominating, we'll count all of X's memory towards each of C, B, and A. So if A, B, and C are all hashes, we could end up with something like what you see.

Ah, okay, thanks. So it should still be the case that the amount retained by roots would be the entire live heap, right? (And, if so, the memory leak I'm looking for would seem to be -- at least mainly -- outside of the MRI heap.)

Thanks again!
